controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    Render.jump(mySprite)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    game.gameOver(false)
})
let mySprite: Sprite = null
tiles.setCurrentTilemap(tilemap`level2`)
color.setColor(1, color.rgb(255, 255, 255))
mySprite = Render.getRenderSpriteVariable()
let myEnemy = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ..........ff............
    .........ffff...........
    ........ffffff..........
    .......ff1ff1ff.........
    .......ffffffff.........
    ........f1f1f1..........
    .........f2f2...........
    ..........ff............
    ..........ff............
    .........ffff...........
    ........ffffff..........
    ......ffffffffff........
    .....f.ffffffff.f.......
    ....f...ffffff...f......
    ...f.....ffff.....f.....
    .........f..f...........
    ........f....f..........
    .......f......f.........
    .......f......f.........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
myEnemy.follow(mySprite)
tiles.placeOnRandomTile(myEnemy, sprites.dungeon.floorLight4)
